import { v4 as crypto } from "uuid";
import CustomerIcon from "@assets/icons/customer-icon";

const list = [
    {
      id: crypto(),
      icon: <CustomerIcon />,
      first_name: "Daniel",
      last_name: "Muñoz",
      phone: 3002852755,
      email: "daniel2002@gmail.com",
      direction: "Calle falsa 123",
      status_count: true,
      time_registered: "12/12/2022",
      total_product_price: 500000,
      products: [
        {
          id: crypto(),
          name: "Gaseosa",
          category: "Gaseosas",
          price: "5000",
          quantity: 15,
        },
        {
          id: crypto(),
          name: "Gaseosa",
          category: "Gaseosas",
          price: "5000",
          quantity: 15,
        },
        {
          id: crypto(),
          name: "Gaseosa",
          category: "Gaseosas",
          price: "5000",
          quantity: 15,
        },
        {
          id: crypto(),
          name: "Gaseosa",
          category: "Gaseosas",
          price: "5000",
          quantity: 15,
        },
        {
          id: crypto(),
          name: "Gaseosa",
          category: "Gaseosas",
          price: "5000",
          quantity: 15,
        },
      ],
    },
    {
      id: crypto(),
      icon: <CustomerIcon />,
      first_name: "Daniel",
      last_name: "Muñoz",
      phone: 3002852755,
      email: "daniel2002@gmail.com",
      direction: "Calle falsa 123",
      status_count: false,
      time_registered: "12/12/2022",
      total_product_price: 0,
    },
    {
      id: crypto(),
      icon: <CustomerIcon />,
      first_name: "Daniel",
      last_name: "Muñoz",
      phone: 3002852755,
      email: "daniel2002@gmail.com",
      direction: "Calle falsa 123",
      status_count: true,
      time_registered: "12/12/2022",
      total_product_price: 80000,
      products: [
        {
          id: crypto(),
          name: "Gaseosa",
          category: "Gaseosas",
          price: "5000",
          quantity: 15,
        },
        {
          id: crypto(),
          name: "Gaseosa",
          category: "Gaseosas",
          price: "5000",
          quantity: 15,
        },
        {
          id: crypto(),
          name: "Gaseosa",
          category: "Gaseosas",
          price: "5000",
          quantity: 15,
        },
        {
          id: crypto(),
          name: "Gaseosa",
          category: "Gaseosas",
          price: "5000",
          quantity: 15,
        },
        {
          id: crypto(),
          name: "Gaseosa",
          category: "Gaseosas",
          price: "5000",
          quantity: 15,
        },
      ],
    },
    {
      id: crypto(),
      icon: <CustomerIcon />,
      first_name: "Daniel",
      last_name: "Muñoz",
      phone: 3002852755,
      email: "daniel2002@gmail.com",
      direction: "Calle falsa 123",
      status_count: false,
      time_registered: "12/12/2022",
      total_product_price: 0,
    },
  ];

  export default list;